export const FRAMES: Frames<AnimationKey> = [
  ['player/waiting.png', 'waiting', 0],
  ['player/landing.png', 'landing', 0],
  ['player/running.png', 'running', 0],
  ['player/back-flip.png', 'backFlip', 0],
  ['player/front-flip.png', 'frontFlip', 0],
  ['player/super-man/1.png', 'superMan', 0],
  ['player/super-man/2.png', 'superMan', 1],
  ['player/super-man/3.png', 'superMan', 2],
  ['player/super-man/4.png', 'superMan', 3],
  ['player/tilt/1.png', 'tilt', 0],
  ['player/tilt/2.png', 'tilt', 1],
  ['player/tilt/3.png', 'tilt', 2],
  ['player/tilt/4.png', 'tilt', 3],
  ['player/tilt/5.png', 'tilt', 4],
  ['player/tilt/6.png', 'tilt', 5],
  ['player/hart-attack/1.png', 'hartAttack', 0],
  ['player/hart-attack/2.png', 'hartAttack', 1],
  ['player/hart-attack/3.png', 'hartAttack', 2],
  ['player/hart-attack/4.png', 'hartAttack', 3],
  ['player/hart-attack/5.png', 'hartAttack', 4],
  ['player/hart-attack/6.png', 'hartAttack', 5],
]
